Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -5,7 +5,7 @@ pool:
   vmImage: 'ubuntu-latest'
 
 variables:
-  terraformVarsFile: 'terraform.tfvars'
+  terraformVarsFile: 'terraform.tfvars'  # Path to your TFvar file in the repository
 
 stages:
 - stage: Terraform
@@ -15,42 +15,40 @@ stages:
     displayName: 'Terraform Deployment'
     steps:
     - script: |
-        echo "Debugging Variables:"
-        echo "Azure Subscription: $(azureSubscription)"
-        echo "Resource Group Name: $(resource_group_name)"
-        echo "AKS Name: $(aks_name)"
-        echo "Storage Account Name: $(storage_account_name)"
-        echo "Container Name: $(container_name)"
-        echo "Log Analytics Workspace Name: $(log_analytics_workspace_name)"
-      displayName: 'Debug Loaded Variables'
-    
-    - script: |
         set -e  # Exit on error
+        
+        echo "Reading Azure Subscription from terraform.tfvars..."
+        export azureSubscription=$(grep 'azureSubscription' $(terraformVarsFile) | cut -d '=' -f2 | tr -d ' "')
+
+        echo "Azure Subscription ID extracted: $azureSubscription"
+
         echo "Logging in to Azure..."
         az login --service-principal -u $(AZURE_CLIENT_ID) -p $(AZURE_CLIENT_SECRET) --tenant $(AZURE_TENANT_ID)
-        az account set --subscription "$(azureSubscription)"
+        
+        echo "Setting Azure subscription to: $azureSubscription"
+        az account set --subscription "$azureSubscription"
         
         echo "Initializing Terraform..."
         terraform init
 
         echo "Checking and importing resources as needed..."
         terraform state show azurerm_resource_group.example || \
-          terraform import azurerm_resource_group.example "/subscriptions/$(azureSubscription)/resourceGroups/$(resource_group_name)"
+          terraform import azurerm_resource_group.example "/subscriptions/$azureSubscription/resourceGroups/$(resource_group_name)"
 
         terraform state show azurerm_kubernetes_cluster.example || \
-          terraform import azurerm_kubernetes_cluster.example "/subscriptions/$(azureSubscription)/resourceGroups/$(resource_group_name)/providers/Microsoft.ContainerService/managedClusters/$(aks_name)"
+          terraform import azurerm_kubernetes_cluster.example "/subscriptions/$azureSubscription/resourceGroups/$(resource_group_name)/providers/Microsoft.ContainerService/managedClusters/$(aks_name)"
 
         terraform state show azurerm_storage_account.example || \
-          terraform import azurerm_storage_account.example "/subscriptions/$(azureSubscription)/resourceGroups/$(resource_group_name)/providers/Microsoft.Storage/storageAccounts/$(storage_account_name)"
+          terraform import azurerm_storage_account.example "/subscriptions/$azureSubscription/resourceGroups/$(resource_group_name)/providers/Microsoft.Storage/storageAccounts/$(storage_account_name)"
 
         terraform state show azurerm_storage_container.example || \
-          terraform import azurerm_storage_container.example "/subscriptions/$(azureSubscription)/resourceGroups/$(resource_group_name)/providers/Microsoft.Storage/storageAccounts/$(storage_account_name)/blobServices/default/containers/$(container_name)"
+          terraform import azurerm_storage_container.example "/subscriptions/$azureSubscription/resourceGroups/$(resource_group_name)/providers/Microsoft.Storage/storageAccounts/$(storage_account_name)/blobServices/default/containers/$(container_name)"
 
         terraform state show azurerm_log_analytics_workspace.example || \
-          terraform import azurerm_log_analytics_workspace.example "/subscriptions/$(azureSubscription)/resourceGroups/$(resource_group_name)/providers/Microsoft.OperationalInsights/workspaces/$(log_analytics_workspace_name)"
+          terraform import azurerm_log_analytics_workspace.example "/subscriptions/$azureSubscription/resourceGroups/$(resource_group_name)/providers/Microsoft.OperationalInsights/workspaces/$(log_analytics_workspace_name)"
 
         terraform state show azurerm_monitor_diagnostic_setting.aks_metrics || \
-          terraform import azurerm_monitor_diagnostic_setting.aks_metrics "/subscriptions/$(azureSubscription)/resourceGroups/$(resource_group_name)/providers/Microsoft.ContainerService/managedClusters/$(aks_name)|aks-metrics-diagnostic-setting2"
+          terraform import azurerm_monitor_diagnostic_setting.aks_metrics "/subscriptions/$azureSubscription/resourceGroups/$(resource_group_name)/providers/Microsoft.ContainerService/managedClusters/$(aks_name)|aks-metrics-diagnostic-setting2"
 
         echo "Running Terraform Plan..."
         terraform plan -var-file=$(terraformVarsFile) -out=tfplan
@@ -63,8 +61,6 @@ stages:
         ARM_CLIENT_ID: $(AZURE_CLIENT_ID)
         ARM_CLIENT_SECRET: $(AZURE_CLIENT_SECRET)
         ARM_TENANT_ID: $(AZURE_TENANT_ID)
-        ARM_SUBSCRIPTION_ID: $(azureSubscription)
-
 
 - stage: DeployMonitoring
   displayName: 'Deploy Monitoring Tools'
@@ -74,16 +70,36 @@ stages:
     displayName: 'Deploy Prometheus and Grafana via Helm'
     steps:
     - script: |
+        set -e  # Exit on error
+
+        echo "Reading Azure Subscription from terraform.tfvars..."
+        export azureSubscription=$(grep 'azureSubscription' $(terraformVarsFile) | cut -d '=' -f2 | tr -d ' "')
+
+        echo "Azure Subscription ID extracted: $azureSubscription"
+
+        echo "Logging in to Azure..."
         az login --service-principal -u $(AZURE_CLIENT_ID) -p $(AZURE_CLIENT_SECRET) --tenant $(AZURE_TENANT_ID)
-        az account set --subscription "$(azureSubscription)"
-        az aks get-credentials --resource-group $(resource_group_name) --name $(aks_name)
         
+        echo "Setting Azure subscription to: $azureSubscription"
+        az account set --subscription "$azureSubscription"
+        
+        echo "Getting AKS credentials..."
+        az aks get-credentials --resource-group $(resource_group_name) --name $(aks_name)
+
+        echo "Installing Helm..."
         curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
+
+        echo "Adding Helm repositories..."
         helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
         helm repo add grafana https://grafana.github.io/helm-charts
         helm repo update
-        
-        helm install grafana grafana/grafana --namespace monitoring \
-          --set adminPassword=$(GRAFANA_ADMIN_PASSWORD) \
-          --set service.type=LoadBalancer
-      displayName: 'Install Prometheus and Grafana'
+
+        echo "Deploying Prometheus and Grafana via Helm..."
+        helm install prometheus prometheus-community/kube-prometheus-stack --namespace monitoring --create-namespace
+        helm install grafana grafana/grafana --namespace monitoring --set adminPassword='yourpassword' --set service.type=LoadBalancer
+
+        echo "Verifying deployments..."
+        kubectl get pods -n monitoring
+      displayName: 'Install Prometheus and Grafana via Helm'
+      env:
+        KUBECONFIG: $(Build.SourcesDirectory)/.kube/config
